services:
  - type: web
    name: barbearia-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barbearia-db
          property: connectionString
  
  - type: web
    name: barbearia-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/projeto-angular
    routes:
      - type: rewrite
        source: /api/*
        destination: https://barbearia-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: barbearia-db
    databaseName: barbeariadoalem_db
    user: barbeariauser